extends:
  - "spectral:oas"
aliases:
  PathItem:
    - $.paths[*]
  OperationObject:
    - "#PathItem[get,put,post,delete,options,head,patch,trace]"
rules:
  # ---------------------------------------------------------------------------
  # Camel Case OperationId
  # ---------------------------------------------------------------------------
  operation-id-camel-case:
    description: Operation IDs must be camelCase since some generators (e.g. RTK Query) don't support kebab-cases.
    message: "Operation ID \"{{value}}\" must be camelCase since some generators (e.g. RTK Query) don't support kebab-cases."
    given: "#OperationObject"
    severity: error
    then:
      field: operationId
      function: casing
      functionOptions:

  # ---------------------------------------------------------------------------
  # Schema rules
  # ---------------------------------------------------------------------------
  info-version-semver:
    severity: error
    recommended: true
    message: Specs should follow semantic versioning. {{value}} is not a valid version.
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: "^([0-9]+.[0-9]+.[0-9]+)$"

  # ---------------------------------------------------------------------------
  # API version Rule
  # ---------------------------------------------------------------------------
  #server-url-must-contain-version:
  #  description: Global API version must be present in the path
  #  severity: error
  #  recommended: true
  #  message: "Unversioned server URL detected: {{value}}"
  #  given: "$.servers[*].url"
  #  then:
  #    function: pattern
  #    functionOptions:
  #      match: "\/v[1-9]+\/"
