name: API Ops with Insomnia and Konnect

on:
  push:
    branches:
      - master

jobs:
  api_quality:
    runs-on: self-hosted
    name: Linting and Testing APIs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: lint
        run: inso lint spec spc_91639e
      - name: test
        run: inso run collection wrk_ea3568
  deploy_to_konnect:
    runs-on: self-hosted
    needs: api_quality
    environment: prod
    name: Deploy the API in Konnect
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inso export
        run: inso export spec spc_91639e -o kong-marketStock.yaml
      - name: deck openapi2kong
        run: /opt/homebrew/bin/deck file openapi2kong --inso-compatible --spec kong-marketStock.yaml -o kong-marketStock-konnect.yaml --select-tag market
      - name: deck reset
        run: /opt/homebrew/bin/deck --konnect-addr https://eu.api.konghq.com  --konnect-token $KONNECT_PAT --konnect-control-plane-name cp-gateway-docker gateway reset --select-tag market -f
      - name: deck sync
        run: /opt/homebrew/bin/deck --konnect-addr https://eu.api.konghq.com  --konnect-token $KONNECT_PAT --konnect-control-plane-name cp-gateway-docker gateway sync --select-tag market kong-marketStock-konnect.yaml
 
      
