name: API Ops with Insomnia and Konnect

on:
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: self-hosted
    name: Linting API
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: lint
        run: inso lint spec -w . market_stock.yaml
  testing:
    runs-on: self-hosted
    needs: linting
    name: Testing API
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test
        run: inso run collection wrk_ea3568
  deploy_to_konnect:
    runs-on: self-hosted
    needs: 
      - linting
      - testing
    environment: prod
    env:
      KONNECT_PAT_ENV: ${{ secrets.KONNECT_PAT }}
    name: Deploy the API in Konnect
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inso export
        run: inso export spec spc_91639e -o kong-marketStock.yaml
      - name: deck openapi2kong
        run: /opt/homebrew/bin/deck file openapi2kong --inso-compatible --spec kong-marketStock.yaml -o kong-marketStock-konnect.yaml --select-tag market
      - name: deck reset
        run: /opt/homebrew/bin/deck --konnect-addr https://eu.api.konghq.com  --konnect-token $KONNECT_PAT_ENV --konnect-control-plane-name cp-gateway-docker gateway reset --select-tag market -f
      - name: deck sync
        run: /opt/homebrew/bin/deck --konnect-addr https://eu.api.konghq.com  --konnect-token $KONNECT_PAT_ENV --konnect-control-plane-name cp-gateway-docker gateway sync --select-tag market kong-marketStock-konnect.yaml
 
      
