name: API Ops with Insomnia and Konnect

on:
  push:
    branches:
      - master

jobs:
  api_quality:
    runs-on: self-hosted
    name: Apply config to Konnect
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: lint
        run: inso lint spec spc_91639e
      - name: test
        run: inso run collection wrk_ea3568
